[web]
port = 8888
encoding = UTF-8
# allow_archive = zip
baseurl = https://vc.compiler.company
contact = ellis
# templates = theme
# style = monoblue
templates = /home/vc/templates
style = gitweb
# pygments_style = tango
highlightfiles = size('<100k')
# highlightonlymatchfilename = True
logourl = https://vc.compiler.company
staticurl = /static
descend = True
collapse = False
allow_push = vc, ellis
[extensions]
# requires pygments to be installed
highlight =
clonebundles =
histedit =
git = 
# external
# hggit = 
[paths]
/core = /home/vc/src/core
/demo = /home/vc/src/demo
/etc = /home/vc/src/etc
/home = /home/vc/src/home
/infra = /home/vc/src/infra/*
/org = /home/vc/src/org/*
/packy = /home/vc/src/packy/
[phases]
publish = False
new-commit = draft