[uwsgi]
master = true
# max-requests = 1000
# logto = {log file path}/hgweb-uwsgi.log
uid = fedora # set process owner
gid = fedora
stats = /run/fedora/stats.sock
chmod-socket = 666
cap = setgid,setuid
# https://www.mercurial-scm.org/wiki/PublishRepositoriesOnNginx
plugins = python
socket = /run/fedora/hgweb.sock
chdir = /home/fedora/
wsgi-file = hgweb.wsgi
# https://stackoverflow.com/questions/15878176/uwsgi-invalid-request-block-size
# http://uwsgi-docs.readthedocs.io/en/latest/ThingsToKnow.html
# buffer-size = 65535
