[web]
port = 8888
encoding = UTF-8
# allow_archive = zip
baseurl = https://vc.compiler.company
contact = ellis
# templates = theme
# style = monoblue
templates = /home/fedora/templates
style = gitweb
# pygments_style = tango
highlightfiles = size('<100k')
# highlightonlymatchfilename = True
logourl = https://vc.compiler.company
staticurl = /static
descend = True
collapse = False
allow_push = vc, ellis, fedora
[extensions]
# requires pygments to be installed
highlight =
clonebundles =
histedit =
git =
evolve = 
# external
# hggit = 
[paths]
/core = /home/fedora/src/core
/demo = /home/fedora/src/demo
/etc = /home/fedora/src/etc
/home = /home/fedora/src/home
/infra = /home/fedora/src/infra/**
/org = /home/fedora/src/org/**
/packy = /home/fedora/src/packy/
[phases]
publish = False
new-commit = draft
[trusted]
users = ellis, vc, root, fedora