[web]
port = 8888
encoding = UTF-8
# allow_archive = zip
baseurl = https://vc.compiler.company
contact = ellis
# templates = theme
# style = monoblue
templates = /home/vc/templates
style = gitweb
# pygments_style = tango
highlightfiles = size('<100k')
# highlightonlymatchfilename = True
logourl = https://vc.compiler.company
staticurl = /static
descend = True
collapse = False
allow_push = ellis
[extensions]
# requires pygments to be installed
highlight =
clonebundles =
histedit =
git = 
# external
# hggit = 
[paths]
/ = /home/vc/src/*
[phases]
publish = False
new-commit = draft