pid_file            "/run/mpd/mpd.pid"
playlist_directory  "/var/lib/mpd/playlists"

# WebDAV setup
music_directory     "https://media.compiler.company/music"

# NFS setup
#music_directory     "nfs://example.com/path/to/your/music/"

# Note the proxy here
database {
    plugin  "proxy"
    host    "media.compiler.company"
    port    "6600"
}

audio_output {
    type  "pipewire"
    name  "pipewire-server"
}